apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello
  name: hello
spec:
  containers:
  - image: valluzzi/hello
    name: hello
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
